/* Benchsy data.
   Derived from benchsy-research.json (research date 2026-07-25) — see
   benchsy-research-sources.md for the primary source behind every model.

   Prices, context windows, release dates and status come from provider
   documentation. The 0-100 capability scores are Benchsy's own normalization
   across this 17-model set, not provider figures: each model carries the
   benchmark basis for every score in `basis`. The scale deliberately leaves
   headroom — the strongest result in the set sits at 98, not 100 — so a
   stronger model can be added later without rescaling the whole board.

   This file is the only product-data source; replace it to move to an API. */

const RESEARCH_DATE = 'July 25, 2026';
/* ISO form of RESEARCH_DATE, used to show the board's age in the hero. */
const RESEARCH_ISO = '2026-07-25';

const SCORE_CATEGORIES = [
  { key: 'coding', label: 'Coding', weight: 0.22, description: 'Software engineering, debugging, and repository-scale agentic work.' },
  { key: 'writing', label: 'Writing', weight: 0.14, description: 'Editing, voice, structure, and long-form professional communication.' },
  { key: 'chat', label: 'Chat', weight: 0.14, description: 'Everyday usefulness, instruction following, and human preference.' },
  { key: 'science', label: 'Science', weight: 0.18, description: 'Math, research reasoning, and hard technical problem solving.' },
  { key: 'computer', label: 'Computer Use', shortLabel: 'Computer', weight: 0.18, description: 'Operating tools, browsers, and desktop interfaces reliably.' },
  { key: 'cybersecurity', label: 'Cybersecurity', shortLabel: 'Cyber', weight: 0.14, description: 'Defensive analysis, secure coding, and vulnerability reasoning.' },
];

const CATEGORIES = [
  { key: 'overall', label: 'Overall', description: 'A weighted composite of the six capabilities below.' },
  ...SCORE_CATEGORIES,
];

const LAB_META = {
  OpenAI: { initials: 'OA', hq: 'San Francisco', note: 'Four current frontier tiers' },
  Anthropic: { initials: 'AN', hq: 'San Francisco', note: 'Writing and agent reliability' },
  Google: { initials: 'GO', hq: 'Mountain View · London', note: 'Multimodal science and speed' },
  xAI: { initials: 'XA', hq: 'Palo Alto', note: 'Fast coding at low output cost' },
  'Moonshot AI': { initials: 'MS', hq: 'Beijing', note: 'Open-weight agentic models' },
  'Zhipu AI': { initials: 'ZP', hq: 'Beijing', note: 'Open-weight coding leader' },
  Alibaba: { initials: 'AL', hq: 'Hangzhou', note: 'Multilingual math and science' },
  DeepSeek: { initials: 'DS', hq: 'Hangzhou', note: 'Frontier reasoning at the lowest price' },
};

/* `change` carries release recency rather than week-over-week movement: the
   research set is a single July 2026 snapshot, so the only signal the data
   actually supports is which models landed in the current month. */
const NEW_IN_SET = { overall: 'NEW', coding: 'NEW', writing: 'NEW', chat: 'NEW', science: 'NEW', computer: 'NEW', cybersecurity: 'NEW' };
const ESTABLISHED = { overall: null, coding: null, writing: null, chat: null, science: null, computer: null, cybersecurity: null };

const rawModels = [
  {
    id: 'claude-fable-5',
    name: 'Claude Fable 5',
    lab: 'Anthropic',
    initials: 'A',
    tier: 'Flagship',
    scores: {
      coding: 97,
      writing: 95,
      chat: 93,
      science: 98,
      computer: 95,
      cybersecurity: 98,
    },
    inputPrice: 10,
    outputPrice: 50,
    context: '1M',
    contextTokens: 1000000,
    speed: 'Deliberate',
    speedScore: 24,
    released: 'Jun 2026',
    status: 'New',
    note: 'New flagship for difficult research, engineering, scientific, and security work; benchmark figures are vendor-reported unless noted.',
    strengths: ['frontier scientific reasoning', 'deep software engineering', 'advanced cyber analysis'],
    weaknesses: ['highest Anthropic price', 'slow, compute-intensive responses'],
    uses: ['hard research problems', 'long-horizon coding agents', 'security research', 'high-stakes analysis'],
    basis: {
      coding: 'Terminal-Bench 2.1, FrontierSWE, SWE Marathon, and PostTrainBench results in the Fable 5 system card; scaled against the same July 2026 frontier set.',
      writing: 'Long-form professional-task quality in GDPval-AA and AA-Briefcase plus Anthropic human-preference evaluations; few writing-only public benchmarks exist.',
      chat: 'Arena-style human preference, instruction-following, and long-context dialogue evidence; normalized below the strongest style-specialized result.',
      science: 'GPQA Diamond, Humanity\'s Last Exam, and Anthropic science/research evaluations; current best-in-class anchor on this 0-100 scale.',
      computer: 'OSWorld, BrowseComp, MCP Atlas, AutomationBench, OfficeQA Pro, and SpreadsheetBench 2 agentic results.',
      cybersecurity: 'KCB 2.0 and Anthropic cyber/CTF system-card evaluations; current high-end anchor, with safeguards considered separately from capability.',
    },
    change: ESTABLISHED,
  },
  {
    id: 'claude-opus-5',
    name: 'Claude Opus 5',
    lab: 'Anthropic',
    initials: 'A',
    tier: 'Flagship',
    scores: {
      coding: 98,
      writing: 97,
      chat: 94,
      science: 97,
      computer: 98,
      cybersecurity: 97,
    },
    inputPrice: 5,
    outputPrice: 25,
    context: '1M',
    contextTokens: 1000000,
    speed: 'Moderate',
    speedScore: 53,
    released: 'Jul 2026',
    status: 'New',
    note: 'Daily-use Opus for complex agentic coding and enterprise work; near-Fable intelligence and leading computer use at half the price.',
    strengths: ['agentic coding', 'professional knowledge work', 'computer-use automation'],
    weaknesses: ['max-effort latency', 'high token verbosity', 'cyber classifier refusals'],
    uses: ['complex codebase work', 'long-horizon research', 'professional document production', 'browser and desktop agents'],
    basis: {
      coding: 'Anthropic reports SWE-bench Verified 96.0%, Pro 79.2%, Multilingual 89.5%, and FrontierBench v0.1 44.4% at xhigh; independently, Cognition measured 53.4% on FrontierCode and Artificial Analysis 89.1% on Terminal-Bench v2.1. Ties the tracked-set ceiling, though Fable 5 leads some long-horizon coding tests.',
      writing: 'Artificial Analysis independently places it first on GDPval-AA v2 (1861 Elo) and AA-Briefcase (1720 Elo), 114 and 146 points above Fable 5. No creative-writing or public human-preference result yet, so this sits just below the tracked-set best rather than above it.',
      chat: 'Provisional: no LMArena or IFBench result published as of this snapshot. Anthropic reports stronger verification and alignment alongside longer answers and more agent-progress narration, which cuts against everyday conversational fit.',
      science: 'Anthropic reports Humanity\'s Last Exam 56.3% without tools and 64.7% with, ArxivMath 91.3%, and IMO 2026 at 42/42; Artificial Analysis independently measured GPQA Diamond 93.2% and CritPt 29.1%. Roughly Fable-level, trailing the strongest GPT and Gemini physics results.',
      computer: 'Anthropic reports state-of-the-art OSWorld 2.0 at 70.6% against Fable 5\'s 66.1% and GPT-5.6 Sol\'s 62.6%, plus BrowseComp 90.8%, MCP-Atlas 85.8%, and Toolathlon Pass@1 80.6% — the strongest agentic results in the tracked set.',
      cybersecurity: 'Safeguards-off system-card evaluations report ExploitBench 70% capability coverage, OSS-Fuzz success on 79.4% of targets, Firefox exploitation 52.4%, and CyScenarioBench 33.7%; well above Opus 4.8 but below the Fable-class anchor. Vendor-reported, with no comparable public GPT/Gemini/Grok runs under these harnesses.',
    },
    change: NEW_IN_SET,
  },
  {
    id: 'claude-opus-4-8',
    name: 'Claude Opus 4.8',
    lab: 'Anthropic',
    initials: 'A',
    tier: 'Flagship',
    scores: {
      coding: 95,
      writing: 97,
      chat: 95,
      science: 95,
      computer: 95,
      cybersecurity: 96,
    },
    inputPrice: 5,
    outputPrice: 25,
    context: '1M',
    contextTokens: 1000000,
    speed: 'Moderate',
    speedScore: 51,
    released: 'May 2026',
    status: 'New',
    note: 'General-purpose Opus flagship immediately below Fable 5; standard API pricing shown.',
    strengths: ['best-in-class writing', 'reliable complex agents', 'balanced frontier reasoning'],
    weaknesses: ['premium price', 'slower than Sonnet-class models'],
    uses: ['professional knowledge work', 'complex coding agents', 'long-form writing', 'computer-use workflows'],
    basis: {
      coding: 'Strong Terminal-Bench 2.1, FrontierSWE, SWE Marathon, and PostTrainBench placement in Anthropic and independent agentic evaluations.',
      writing: 'Top-tier GDPval-AA and AA-Briefcase professional deliverables plus strong human preference for editing, voice, and long-form synthesis.',
      chat: 'High Arena-style human preference and instruction-following quality; especially strong conversational tone and nuanced assistance.',
      science: 'GPQA Diamond, Humanity\'s Last Exam, and research-agent results; slightly below Fable 5 and the best high-compute science models.',
      computer: 'OSWorld, BrowseComp, MCP Atlas, AutomationBench, OfficeQA Pro, and SpreadsheetBench 2 indicate elite general agent performance.',
      cybersecurity: 'Anthropic cyber system-card and KCB 2.0 evidence show very high exploit and security-reasoning capability, just below Fable 5.',
    },
    change: ESTABLISHED,
  },
  {
    id: 'claude-sonnet-5',
    name: 'Claude Sonnet 5',
    lab: 'Anthropic',
    initials: 'A',
    tier: 'Balanced',
    scores: {
      coding: 94,
      writing: 93,
      chat: 94,
      science: 92,
      computer: 93,
      cybersecurity: 80,
    },
    inputPrice: 3,
    outputPrice: 15,
    context: '1M',
    contextTokens: 1000000,
    speed: 'Fast',
    speedScore: 74,
    released: 'Jun 2026',
    status: 'New',
    note: 'Standard list price is shown; Anthropic has temporary launch pricing of $2 input and $10 output through 2026-08-31.',
    strengths: ['excellent price-performance', 'fast agentic coding', 'strong follow-through'],
    weaknesses: ['lower cyber ceiling than Opus', 'launch price is temporary'],
    uses: ['production coding agents', 'enterprise automation', 'high-volume analysis', 'interactive assistants'],
    basis: {
      coding: 'Anthropic cost-performance curves and partner evaluations show Opus-class sustained coding, tool use, debugging, and brownfield issue resolution.',
      writing: 'Professional-task and human-preference evidence; close to Opus quality but optimized more heavily for execution speed and cost.',
      chat: 'Human-preference and instruction-following evidence plus efficient conversational behavior; normalized near the top of the field.',
      science: 'GPQA/HLE-family reasoning and general knowledge evidence; strong frontier result but below the highest-compute science flagships.',
      computer: 'OSWorld and BrowseComp cost-performance curves plus multi-step tool-use partner evaluations indicate near-Opus execution quality.',
      cybersecurity: 'Anthropic reports materially lower cyber capability than its Opus models; scaled conservatively from system-card cyber evaluations.',
    },
    change: ESTABLISHED,
  },
  {
    id: 'claude-haiku-4-5',
    name: 'Claude Haiku 4.5',
    lab: 'Anthropic',
    initials: 'A',
    tier: 'Efficient',
    scores: {
      coding: 82,
      writing: 84,
      chat: 86,
      science: 79,
      computer: 81,
      cybersecurity: 66,
    },
    inputPrice: 1,
    outputPrice: 5,
    context: '200K',
    contextTokens: 200000,
    speed: 'Blazing',
    speedScore: 94,
    released: 'Oct 2025',
    status: 'Stable',
    note: 'Anthropic\'s fastest current small model; smaller context and lower reasoning ceiling than the 2026 Claude flagships.',
    strengths: ['very low latency', 'low Anthropic cost', 'good lightweight tool use'],
    weaknesses: ['200K context', 'older and less capable', 'limited hard reasoning'],
    uses: ['classification and routing', 'real-time chat', 'high-volume extraction', 'simple agents'],
    basis: {
      coding: 'SWE-bench Verified and agentic coding evidence from Anthropic\'s Haiku 4.5 system card; normalized well below 2026 frontier flagships.',
      writing: 'Human-preference and instruction-following evidence supports polished short-form output, with less depth on long professional deliverables.',
      chat: 'Fast conversational instruction following and Anthropic human-preference evaluations; latency helps interaction but not raw capability score.',
      science: 'GPQA Diamond and general reasoning evaluations in the system card; capable but meaningfully behind newer high-compute models.',
      computer: 'Computer-use and tool-use evaluations show useful low-latency agency, limited by smaller reasoning and context budgets.',
      cybersecurity: 'System-card cyber evaluations and model scale imply a much lower advanced CTF/exploit ceiling than Opus/Fable models.',
    },
    change: ESTABLISHED,
  },
  {
    id: 'gpt-5-6-sol',
    name: 'GPT-5.6 Sol',
    lab: 'OpenAI',
    initials: 'O',
    tier: 'Flagship',
    scores: {
      coding: 98,
      writing: 94,
      chat: 94,
      science: 98,
      computer: 98,
      cybersecurity: 98,
    },
    inputPrice: 5,
    outputPrice: 30,
    context: '1.05M',
    contextTokens: 1050000,
    speed: 'Deliberate',
    speedScore: 39,
    released: 'Jul 2026',
    status: 'New',
    note: 'Current highest-capability GPT-5.6 tier and OpenAI\'s flagship for professional work; standard API pricing shown.',
    strengths: ['top agentic coding', 'frontier science reasoning', 'elite computer and cyber work'],
    weaknesses: ['high output cost', 'deliberate latency', 'some cyber tasks trigger safeguards'],
    uses: ['autonomous software engineering', 'scientific research', 'complex computer use', 'cybersecurity analysis'],
    basis: {
      coding: 'State-of-the-art vendor-reported Terminal-Bench 2.1 plus strong SWE Marathon, FrontierSWE, and professional coding-agent results.',
      writing: 'GDPval-AA, AA-Briefcase, and professional deliverable evaluations; excellent precision, though Claude Opus remains the style anchor.',
      chat: 'Human preference, instruction following, and professional assistant evaluations; strong but optimized more for work than casual style.',
      science: 'GeneBench Pro, GPQA Diamond, Humanity\'s Last Exam, and expert science tasks place Sol at the current frontier anchor.',
      computer: 'BrowseComp, OfficeQA Pro, SpreadsheetBench 2, MCP Atlas, AutomationBench, and first-party computer/tool-use evaluations.',
      cybersecurity: 'ExploitBench, ExploitGym, KCB 2.0, and professional cyber evaluations support a current best-in-class estimate.',
    },
    change: NEW_IN_SET,
  },
  {
    id: 'gpt-5-6-terra',
    name: 'GPT-5.6 Terra',
    lab: 'OpenAI',
    initials: 'O',
    tier: 'Balanced',
    scores: {
      coding: 95,
      writing: 92,
      chat: 93,
      science: 95,
      computer: 94,
      cybersecurity: 93,
    },
    inputPrice: 2.5,
    outputPrice: 15,
    context: '1.05M',
    contextTokens: 1050000,
    speed: 'Moderate',
    speedScore: 62,
    released: 'Jul 2026',
    status: 'New',
    note: 'Balanced GPT-5.6 tier for everyday professional and agentic workloads.',
    strengths: ['excellent all-rounder', 'strong coding agents', 'one-million-token context'],
    weaknesses: ['not the family maximum', 'still premium-priced'],
    uses: ['general enterprise AI', 'coding copilots', 'document analysis', 'multi-tool agents'],
    basis: {
      coding: 'GPT-5.6 family Terminal-Bench and software-agent evidence, discounted from Sol for its lower-compute tier.',
      writing: 'Professional deliverable, instruction-following, and human-preference evidence; strong balance of quality and response cost.',
      chat: 'OpenAI human-preference and instruction-following evaluations; balanced tier is especially suitable for general assistants.',
      science: 'GPT-5.6 family GPQA/HLE/GeneBench evidence, conservatively normalized below Sol\'s maximum-reasoning results.',
      computer: 'GPT-5.6 family BrowseComp and office/tool-use evaluations, adjusted for the balanced compute tier.',
      cybersecurity: 'GPT-5.6 family ExploitBench/ExploitGym evidence, scaled below Sol because tier-specific public results are limited.',
    },
    change: NEW_IN_SET,
  },
  {
    id: 'gpt-5-6-luna',
    name: 'GPT-5.6 Luna',
    lab: 'OpenAI',
    initials: 'O',
    tier: 'Efficient',
    scores: {
      coding: 90,
      writing: 89,
      chat: 91,
      science: 89,
      computer: 90,
      cybersecurity: 86,
    },
    inputPrice: 1,
    outputPrice: 6,
    context: '1.05M',
    contextTokens: 1050000,
    speed: 'Fast',
    speedScore: 83,
    released: 'Jul 2026',
    status: 'New',
    note: 'Fastest and lowest-cost GPT-5.6 tier; tier-specific public benchmark disclosure is limited, so estimates are conservative.',
    strengths: ['fast GPT-5.6 responses', 'low price', 'very long context'],
    weaknesses: ['lower hard-reasoning ceiling', 'limited tier-specific benchmark data'],
    uses: ['interactive applications', 'high-volume assistants', 'document processing', 'routine coding'],
    basis: {
      coding: 'GPT-5.6 family software-engineering evidence adjusted downward for the low-cost, low-latency compute tier.',
      writing: 'OpenAI instruction-following and professional-task evidence; fewer tier-specific writing results are public.',
      chat: 'Human-preference and instruction-following evidence plus fast interactive latency; raw quality remains below Terra and Sol.',
      science: 'GPT-5.6 family GPQA/HLE evidence, scaled conservatively because Luna-specific maximum-reasoning results are not published.',
      computer: 'GPT-5.6 family tool-use and computer-task results adjusted for the faster, cheaper inference tier.',
      cybersecurity: 'Family ExploitBench/ExploitGym evidence with a conservative tier discount; no comprehensive Luna-only cyber table is public.',
    },
    change: NEW_IN_SET,
  },
  {
    id: 'gpt-5-5-pro',
    name: 'GPT-5.5 Pro',
    lab: 'OpenAI',
    initials: 'O',
    tier: 'Reasoning',
    scores: {
      coding: 96,
      writing: 92,
      chat: 92,
      science: 97,
      computer: 83,
      cybersecurity: 95,
    },
    inputPrice: 30,
    outputPrice: 180,
    context: '1.05M',
    contextTokens: 1050000,
    speed: 'Deliberate',
    speedScore: 13,
    released: 'Apr 2026',
    status: 'Stable',
    note: 'Highest-compute GPT-5.5 reasoning tier, retained as the fourth current flagship option alongside the newer GPT-5.6 family; it does not expose native computer use.',
    strengths: ['maximum-depth reasoning', 'elite science', 'hard coding problems'],
    weaknesses: ['extremely expensive', 'slowest OpenAI tier', 'no native computer use'],
    uses: ['rare hardest problems', 'expert scientific analysis', 'deep code investigation'],
    basis: {
      coding: 'FrontierSWE, PostTrainBench, Terminal-Bench, and long-horizon coding-agent evaluations; still elite but superseded by GPT-5.6 Sol.',
      writing: 'GDPval-AA, AA-Briefcase, and professional deliverable evidence; high quality but expensive and slower than newer tiers.',
      chat: 'Instruction-following and human-preference evidence, with latency and over-deliberation reducing suitability for ordinary chat.',
      science: 'GPQA Diamond, Humanity\'s Last Exam, and high-compute expert reasoning results; near the frontier science anchor.',
      computer: 'Strong browser/agent reasoning on BrowseComp-style tasks, but the official model lacks native computer-use support.',
      cybersecurity: 'KCB 2.0 and high-compute security-reasoning evidence; below the newer Sol/Opus/Fable frontier.',
    },
    change: ESTABLISHED,
  },
  {
    id: 'grok-4-5',
    name: 'Grok 4.5',
    lab: 'xAI',
    initials: 'X',
    tier: 'Flagship',
    scores: {
      coding: 97,
      writing: 90,
      chat: 92,
      science: 93,
      computer: 93,
      cybersecurity: 93,
    },
    inputPrice: 2,
    outputPrice: 6,
    context: '500K',
    contextTokens: 500000,
    speed: 'Fast',
    speedScore: 84,
    released: 'Jul 2026',
    status: 'New',
    note: 'New xAI flagship; official benchmark numbers are vendor-reported and reflect selected agent harnesses.',
    strengths: ['fast frontier coding', 'strong terminal agents', 'low output price'],
    weaknesses: ['500K context trails leaders', 'many results are vendor-reported'],
    uses: ['coding agents', 'terminal automation', 'technical research', 'fast reasoning APIs'],
    basis: {
      coding: 'DeepSWE 1.0 62%, DeepSWE 1.1 53%, SWE Marathon 29%, Terminal-Bench 2.1 83.3%, and SWE-Bench Pro 64.7% reported by xAI.',
      writing: 'Arena-style preference and professional-generation evidence; fewer writing-only public evaluations than for Claude or GPT flagships.',
      chat: 'Strong human-preference placement and conversational personality, normalized below the most consistent general-assistant leaders.',
      science: 'GPQA Diamond, AIME/HMMT-family math, and frontier reasoning results reported in xAI\'s launch materials.',
      computer: 'Terminal-Bench 2.1, agentic software work, tool calling, and research-agent evidence indicate high autonomous execution ability.',
      cybersecurity: 'CTF/KCB-style and terminal-agent evidence supports a high estimate; comprehensive independent cyber reporting remains limited.',
    },
    change: NEW_IN_SET,
  },
  {
    id: 'grok-4-1-fast',
    name: 'Grok 4.1 Fast Reasoning',
    lab: 'xAI',
    initials: 'X',
    tier: 'Efficient',
    scores: {
      coding: 87,
      writing: 87,
      chat: 90,
      science: 88,
      computer: 90,
      cybersecurity: 84,
    },
    inputPrice: 0.2,
    outputPrice: 0.5,
    context: '2M',
    contextTokens: 2000000,
    speed: 'Blazing',
    speedScore: 96,
    released: 'Nov 2025',
    status: 'Stable',
    note: 'Latest established fast/reasoning Grok tier alongside Grok 4.5; standard cache-miss API pricing shown.',
    strengths: ['exceptional throughput', 'two-million-token context', 'very low cost'],
    weaknesses: ['below flagship reasoning depth', 'limited independent cyber data'],
    uses: ['real-time agents', 'web research', 'massive-context processing', 'budget APIs'],
    basis: {
      coding: 'BFCL v4 and xAI coding/tool-use evaluations; optimized for throughput rather than maximum software-engineering depth.',
      writing: 'General human-preference and instruction-following evidence; competent but less nuanced than premium frontier models.',
      chat: 'Fast interactive behavior and human-preference evidence make it a strong chat model despite a lower hard-reasoning ceiling.',
      science: 'Grok Fast-family GPQA Diamond 85.7 and AIME 92 evidence, normalized against newer July 2026 models.',
      computer: 'BFCL v4 72%, research-agent 63.9%, FRAMES 87.6%, and X Browse 56.3% reported by xAI.',
      cybersecurity: 'Tool-use and terminal reasoning imply solid defensive analysis; limited model-specific Cybench/CTF disclosure lowers confidence.',
    },
    change: ESTABLISHED,
  },
  {
    id: 'gemini-3-1-pro',
    name: 'Gemini 3.1 Pro Preview',
    lab: 'Google',
    initials: 'G',
    tier: 'Flagship',
    scores: {
      coding: 93,
      writing: 91,
      chat: 92,
      science: 96,
      computer: 89,
      cybersecurity: 86,
    },
    inputPrice: 2,
    outputPrice: 12,
    context: '1.05M',
    contextTokens: 1048576,
    speed: 'Moderate',
    speedScore: 49,
    released: 'Feb 2026',
    status: 'Preview',
    note: 'Latest currently available Gemini Pro tier; preview model. Price shown is the standard rate for prompts up to 200K tokens; longer prompts cost $4 input and $18 output per million.',
    strengths: ['excellent multimodal science', 'long-context synthesis', 'strong coding'],
    weaknesses: ['preview lifecycle', 'higher long-prompt pricing', 'moderate latency'],
    uses: ['multimodal research', 'large-document analysis', 'scientific reasoning', 'complex app prototyping'],
    basis: {
      coding: 'SWE-bench/Terminal-Bench-family agentic coding and Google vibe-coding evaluations; strong but below the July coding leaders.',
      writing: 'Professional multimodal generation, instruction following, and human-preference evidence; strong synthesis with some verbosity variance.',
      chat: 'Arena-style human preference and multimodal assistant quality support a near-frontier conversational score.',
      science: 'GPQA Diamond, Humanity\'s Last Exam, MMMU-Pro, and long-context scientific reasoning are among the model\'s strongest areas.',
      computer: 'Agentic tool use, custom tools, BrowseComp-style research, and multimodal interface reasoning; no dedicated native computer-use model claim.',
      cybersecurity: 'Strong general reasoning and code analysis, but limited model-specific Cybench/CTF disclosure; scored conservatively.',
    },
    change: ESTABLISHED,
  },
  {
    id: 'gemini-3-6-flash',
    name: 'Gemini 3.6 Flash',
    lab: 'Google',
    initials: 'G',
    tier: 'Efficient',
    scores: {
      coding: 92,
      writing: 89,
      chat: 91,
      science: 91,
      computer: 94,
      cybersecurity: 88,
    },
    inputPrice: 1.5,
    outputPrice: 7.5,
    context: '1.05M',
    contextTokens: 1048576,
    speed: 'Blazing',
    speedScore: 92,
    released: 'Jul 2026',
    status: 'New',
    note: 'Just-launched stable fast tier; Google reports improved quality and token efficiency over Gemini 3.5 Flash.',
    strengths: ['excellent speed-quality ratio', 'strong computer use', 'one-million-token context'],
    weaknesses: ['very new independent evidence', 'less deep than Pro on hard science'],
    uses: ['real-time multimodal apps', 'computer-use agents', 'high-volume coding', 'long-context chat'],
    basis: {
      coding: 'Google agentic coding and code-generation evaluations show near-Pro capability at Flash latency; independent post-launch data is still sparse.',
      writing: 'Human-preference, instruction-following, and multimodal generation evidence; concise and efficient rather than style-leading.',
      chat: 'Fast multimodal dialogue and human-preference evidence; optimized for responsive assistant workloads.',
      science: 'GPQA/MMMU/HLE-family evidence reported at launch, scaled below Pro and high-compute science flagships.',
      computer: 'Google reports improved OSWorld performance and computer-use efficiency, making agentic GUI work a standout capability.',
      cybersecurity: 'Strong code and agent reasoning, but it is not the separate 3.5 Flash Cyber specialist; limited public Cybench data.',
    },
    change: NEW_IN_SET,
  },
  {
    id: 'glm-5-2',
    name: 'GLM-5.2',
    lab: 'Zhipu AI',
    initials: 'Z',
    tier: 'Open weights',
    scores: {
      coding: 96,
      writing: 89,
      chat: 89,
      science: 91,
      computer: 92,
      cybersecurity: 88,
    },
    inputPrice: 1.4,
    outputPrice: 4.4,
    context: '1M',
    contextTokens: 1000000,
    speed: 'Moderate',
    speedScore: 59,
    released: 'Jun 2026',
    status: 'New',
    note: 'Latest GLM flagship. Official Z.ai API pricing is used; open weights are also available.',
    strengths: ['open-weight coding leader', 'low hosted price', 'one-million-token context'],
    weaknesses: ['less independent chat data', 'uneven third-party hosting speeds'],
    uses: ['open-model coding agents', 'self-hosted enterprise AI', 'bilingual workflows', 'cost-efficient automation'],
    basis: {
      coding: 'FrontierSWE trails Claude Opus 4.8 by about 1 point and exceeds GPT-5.5 by about 1; also strong Code Arena, DeepSWE, ProgramBench, and PostTrainBench results.',
      writing: 'Professional deliverable and bilingual generation evidence; fewer independent English style-preference results than Western flagships.',
      chat: 'General preference, instruction-following, and bilingual assistant evidence; normalized below the strongest established chat models.',
      science: 'GPQA/HLE/math and general expert-reasoning results in the GLM-5.2 report; highly capable but not the science anchor.',
      computer: 'OfficeQA Pro, SpreadsheetBench 2, MCP Atlas, AutomationBench, BrowseComp, and long-horizon coding-agent evidence.',
      cybersecurity: 'KCB 2.0, coding, and terminal-agent evidence support a strong estimate; public safety/cyber detail is thinner than Anthropic or OpenAI.',
    },
    change: ESTABLISHED,
  },
  {
    id: 'qwen-3-7-max',
    name: 'Qwen3.7-Max',
    lab: 'Alibaba',
    initials: 'Q',
    tier: 'Flagship',
    scores: {
      coding: 94,
      writing: 90,
      chat: 90,
      science: 95,
      computer: 92,
      cybersecurity: 88,
    },
    inputPrice: 2.5,
    outputPrice: 7.5,
    context: '1M',
    contextTokens: 1000000,
    speed: 'Moderate',
    speedScore: 65,
    released: 'May 2026',
    status: 'New',
    note: 'Latest Qwen Max flagship. Alibaba Cloud Model Studio international standard pricing is used, excluding temporary regional discounts.',
    strengths: ['excellent math and science', 'strong multilingual coding', 'one-million-token context'],
    weaknesses: ['can be verbose', 'limited cyber-specific evidence'],
    uses: ['multilingual agents', 'math and science', 'long-context coding', 'Alibaba Cloud deployments'],
    basis: {
      coding: 'SWE-Bench Verified 80.4 and Terminal-Bench 2.0-Terminus 69.7 reported by Together, plus Alibaba agentic coding evaluations.',
      writing: 'Strong multilingual and long-form generation with good instruction following; style-preference evidence is less extensive than Arena leaders.',
      chat: 'Multilingual assistant and preference evidence; strong general interaction, with verbosity noted by Artificial Analysis.',
      science: 'GPQA Diamond 92.4 and HMMT February 2026 97.1 reported by Together, plus Alibaba reasoning benchmarks.',
      computer: 'Terminal-Bench, agentic tool use, browser/research workflows, and Alibaba\'s agent-frontier evaluations.',
      cybersecurity: 'High coding and terminal scores imply strong security reasoning; sparse model-specific Cybench/CTF reporting keeps the estimate below leaders.',
    },
    change: ESTABLISHED,
  },
  {
    id: 'deepseek-v4-pro',
    name: 'DeepSeek-V4-Pro Preview',
    lab: 'DeepSeek',
    initials: 'D',
    tier: 'Flagship',
    scores: {
      coding: 93,
      writing: 88,
      chat: 89,
      science: 94,
      computer: 89,
      cybersecurity: 90,
    },
    inputPrice: 0.435,
    outputPrice: 0.87,
    context: '1M',
    contextTokens: 1000000,
    speed: 'Deliberate',
    speedScore: 46,
    released: 'Apr 2026',
    status: 'Preview',
    note: 'Latest DeepSeek flagship API model and hybrid thinking/non-thinking preview; official cache-miss price is used.',
    strengths: ['exceptional API value', 'strong hybrid reasoning', 'one-million-token context'],
    weaknesses: ['preview stability', 'limited independent V4-Pro results', 'deliberate at high reasoning'],
    uses: ['budget reasoning APIs', 'coding and math', 'bilingual analysis', 'long-context agents'],
    basis: {
      coding: 'DeepSeek\'s V4-Pro launch coding and agent benchmarks plus public software-engineering comparisons; preview status and limited independent replication reduce confidence.',
      writing: 'Strong long-context and bilingual generation, but limited current Arena writing-style evidence for the Pro preview.',
      chat: 'Hybrid thinking supports flexible conversation; scored conservatively from instruction-following and general preference evidence.',
      science: 'DeepSeek reasoning-family GPQA, math, and expert-domain evidence, with V4-Pro positioned as its strongest current reasoner.',
      computer: 'Launch emphasis on stronger agent capabilities, coding, and tool use; no comprehensive independent OSWorld table was available.',
      cybersecurity: 'Strong code reasoning and agent autonomy imply high CTF/security potential; limited V4-Pro-specific Cybench disclosure caps the score.',
    },
    change: ESTABLISHED,
  },
  {
    id: 'kimi-k3',
    name: 'Kimi K3',
    lab: 'Moonshot AI',
    initials: 'K',
    tier: 'Flagship',
    scores: {
      coding: 97,
      writing: 93,
      chat: 91,
      science: 93,
      computer: 96,
      cybersecurity: 90,
    },
    inputPrice: 3,
    outputPrice: 15,
    context: '1M',
    contextTokens: 1000000,
    speed: 'Deliberate',
    speedScore: 43,
    released: 'Jul 2026',
    status: 'New',
    note: 'API is live; full open weights were announced for 2026-07-27. Standard cache-miss input pricing is shown; cached input is $0.30 per million tokens.',
    strengths: ['elite coding agents', 'excellent office automation', 'one-million-token open model'],
    weaknesses: ['high output price', 'very new ecosystem', 'many benchmarks are vendor-run'],
    uses: ['autonomous coding', 'office and spreadsheet agents', 'long-horizon research', 'open-weight deployment'],
    basis: {
      coding: 'DeepSWE v1.1 67.3 plus Kimi\'s Terminal-Bench 2.1, ProgramBench, SWE Marathon, FrontierSWE, PostTrainBench, MLS Bench Lite, and KCB 2.0 table.',
      writing: 'OfficeQA Pro, SpreadsheetBench 2, GDPval-AA, AA-Briefcase, and Kimi\'s professional artifact-generation evaluations.',
      chat: 'Human-preference and instruction-following evidence plus strong knowledge-work interaction; fewer mature Arena samples because it is newly launched.',
      science: 'Kimi\'s full GPQA/HLE/math and multimodal benchmark table, including MMMU-Pro and PerceptionBench; scaled below the science leaders.',
      computer: 'OfficeQA Pro, SpreadsheetBench 2, MCP Atlas, AutomationBench, BrowseComp 90.4 without context management, and strong agentic coding results.',
      cybersecurity: 'KCB 2.0 and terminal/coding-agent evidence show high security-task competence; results are primarily vendor-run.',
    },
    change: NEW_IN_SET,
  },
];

const overallScore = (scores) => SCORE_CATEGORIES.reduce(
  (total, category) => total + scores[category.key] * category.weight,
  0,
);

const MODELS = rawModels.map((model) => ({
  ...model,
  scores: { overall: Number(overallScore(model.scores).toFixed(1)), ...model.scores },
  price: `$${model.inputPrice.toFixed(2)} in · $${model.outputPrice.toFixed(2)} out`,
  bestAt: model.strengths.join(' · '),
  watchOut: model.weaknesses.join(' · '),
}));

/* Recent, sourced changes to the field — releases and pricing facts drawn from
   the same provider documentation as the model records. */
const FEED = [
  { type: 'new', text: 'Anthropic shipped Claude Opus 5 at Opus 4.8 pricing — $5 in and $25 out — with state-of-the-art OSWorld 2.0 computer use and near-Fable reasoning at half Fable’s price.', time: 'Jul 2026' },
  { type: 'new', text: 'OpenAI shipped GPT-5.6 in three tiers — Sol, Terra and Luna — each with roughly one million tokens of context.', time: 'Jul 2026' },
  { type: 'new', text: 'Kimi K3 went live on the Moonshot API, with full open weights announced for July 27.', time: 'Jul 2026' },
  { type: 'new', text: 'Grok 4.5 became the xAI flagship at $2 in and $6 out per million — the lowest output price among the frontier models tracked.', time: 'Jul 2026' },
  { type: 'new', text: 'Gemini 3.6 Flash replaced 3.5 Flash as Google’s stable fast tier, with better token efficiency.', time: 'Jul 2026' },
  { type: 'price', text: 'Claude Sonnet 5 is running launch pricing of $2 in and $10 out through August 31, below its $3 / $15 list price.', time: 'Jun 2026' },
  { type: 'price', text: 'DeepSeek-V4-Pro Preview remains the cheapest model on the board at $0.44 in and $0.87 out per million.', time: 'Apr 2026' },
];

/* Primary sources, grouped for the methodology dialog. */
const SOURCES = [
  { label: 'Anthropic', items: [
    { name: 'Claude models overview', url: 'https://platform.claude.com/docs/en/about-claude/models/overview' },
    { name: 'Anthropic pricing', url: 'https://platform.claude.com/docs/en/about-claude/pricing' },
    { name: 'System cards and evaluations', url: 'https://platform.claude.com/docs/en/resources/overview' },
  ] },
  { label: 'OpenAI', items: [
    { name: 'GPT-5.6 launch and benchmarks', url: 'https://openai.com/index/gpt-5-6/' },
    { name: 'API model catalog', url: 'https://developers.openai.com/api/docs/models' },
  ] },
  { label: 'Google', items: [
    { name: 'Gemini API model pages', url: 'https://ai.google.dev/gemini-api/docs/models/gemini-3.1-pro-preview' },
    { name: 'Gemini API pricing', url: 'https://ai.google.dev/gemini-api/docs/pricing' },
  ] },
  { label: 'xAI', items: [
    { name: 'Grok 4.5 launch and benchmarks', url: 'https://x.ai/news/grok-4-5' },
    { name: 'xAI model catalog', url: 'https://docs.x.ai/developers/models' },
  ] },
  { label: 'Other labs', items: [
    { name: 'GLM-5.2 (Zhipu AI)', url: 'https://z.ai/blog/glm-5.2' },
    { name: 'Qwen3.7-Max (Alibaba)', url: 'https://www.alibabacloud.com/help/en/model-studio/model-pricing' },
    { name: 'DeepSeek-V4-Pro pricing', url: 'https://api-docs.deepseek.com/quick_start/pricing/' },
    { name: 'Kimi K3 (Moonshot AI)', url: 'https://www.kimi.com/blog/kimi-k3' },
  ] },
  { label: 'Cross-model benchmarks', items: [
    { name: 'LMArena human preference', url: 'https://huggingface.co/spaces/lmarena-ai/arena-leaderboard' },
    { name: 'OSWorld computer use', url: 'https://osworld-v1.xlang.ai/' },
    { name: 'Cybench', url: 'https://cybench.github.io/' },
    { name: 'Terminal-Bench 2.1', url: 'https://artificialanalysis.ai/evaluations/terminalbench-v2-1' },
  ] },
];
